language: node_js

node_js:
  - node

cache:
  directories:
    - ~/build/CanDIG/go-model-service/node_modules

addons:
  apt:
    packages:
    - docker-ce

services:
 - docker

before_install:
 - npm root
 - docker --version
 - cp default.env .env

install:
 - docker-compose up --detach
 - ./migrate.sh

before_script:
 - npm install newman
 - ~/build/CanDIG/go-model-service/node_modules/.bin/newman --version

script:
 - ~/build/CanDIG/go-model-service/node_modules/.bin/newman run ./tests/go-model-service.postman_collection.json -d tests/postman-data.csv
