language: go
go_import_path: github.com/CanDIG/go-model-service

go:
  - "1.9"
  - "1.10.x"

cache:
  directories:
    - ~/node_modules
    - ~/.nvm

addons:
  apt:
    packages:
    - nodejs
    - npm
    - docker-ce
    update: true

services:
 - docker

before_install:
 - docker --version
 - cp default.env .env

install:
 - docker-compose up --detach
 - ./migrate.sh

before_script:
 - npm install newman
 - node --version
 - npm --version
 - /home/travis/node_modules/.bin/newman --version

script:
 - /home/travis/node_modules/.bin/newman run ./tests/go-model-service.postman_collection.json -d tests/postman-data.csv
