language: go
go_import_path: github.com/CanDIG/go-model-service

go:
  - "1.9"
  - "1.10.x"

cache:
  directories:
    - ~/node_modules
    - ~/.nvm

addons:
  apt:
    packages:
    - nodejs
    - npm
    - docker-ce

services:
  - docker

before_install:
 - docker --version
 - cp default.env .env
 - npm install -g dredd
 - sudo pip install dredd_hooks

install:
 - docker-compose build
 - docker-compose up

script:
 - dredd --config model-vs/api/dredd.yml --hookfiles model-vs/api/dreddhooks.py -l warning
