# Build from project root with:
#     docker-compose up
# or, with forced re-build of apps:
#     docker-compose up --force-recreate --build

version: "3.7"
services:
  database:
    # Use postgres 11.7 image to match stable postgres-client debian
    image: "postgres:11.7-alpine"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
  gms-webapp:
    build:
      context: .
      target: webapp
      args:
        - API_PATH=${PROJECT_ROOT}/model-vs/api
    env_file:
      - .env
    environment:
      - POP_PATH=${PROJECT_ROOT}
      - APP_PATH=${PROJECT_ROOT}/model-vs
    depends_on:
      - database
    ports:
      - "3000:3000"
volumes:
  database-data: