# Build from project root with:
#   docker-compose up

# TODO write documentation pertaining to the .env file in the README
# TODO replace ${GOPATH_SPECIAL} with ${GOPATH} when a better bugfix it found

version: "3.8"
services:
  gms-webapp:
    build:
      context: .
      target: webapp
    env_file:
      - .env
    environment:
      - POP_PATH=${GOPATH_SPECIAL}/src/github.com/CanDIG/go-model-service
      - API_PATH=${GOPATH_SPECIAL}/src/github.com/CanDIG/go-model-service/model-vs/api
    volumes:
      - .:${GOPATH_SPECIAL}/src/github.com/CanDIG/go-model-service
    ports:
      - "3000"