# Build from project root with:
#   docker-compose up

# TODO write documentation pertaining to the .env file in the README
# TODO replace ${GOPATH_SPECIAL} with ${GOPATH} when a better bugfix it found

version: "3.7"
services:
  gms-webapp:
    build:
      context: .
      target: webapp
      args:
        - API_PATH=${PROJECT_ROOT}/model-vs/api
    env_file:
      - .env
    environment:
      - POP_PATH=${PROJECT_ROOT}
      - APP_PATH=${PROJECT_ROOT}/model-vs
    ports:
      - "3000:3000"