dry-run: null
language: python
server-wait: 2
init: false
custom: {}
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 500
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
config: ./model-vs/api/dredd.yml
hookfiles: ./model-vs/api/dreddhooks.py
blueprint: ./model-vs/api/swagger.yml
hooks-worker-handler-host: 127.0.0.1
endpoint: 'http://0.0.0.0:3000'
