// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/mauricelam/genny

package generics

import (
	"github.com/gobuffalo/pop"

	datamodels "github.com/CanDIG/go-model-service/variant-service/data/models"
)

// getindividualByID returns the Individual in the database corresponding to the given ID (or nil if no match is found)
func getindividualByID(id string, tx *pop.Connection) (*datamodels.Individual, error) {
	var individual *datamodels.Individual
	err := tx.Find(individual, id)
	return individual, err
}

// getvariantByID returns the Variant in the database corresponding to the given ID (or nil if no match is found)
func getvariantByID(id string, tx *pop.Connection) (*datamodels.Variant, error) {
	var individual *datamodels.Variant
	err := tx.Find(individual, id)
	return individual, err
}
