# This is the API definition that acts as the template for go-swagger to auto-generate
# boilerplate go code. 
# For a simple todo-list server tutorial that explains the swagger definitions, see:
# https://goswagger.io/tutorial/todo-list.html
# For go-swagger developer instructions and a description of the structure of the `api` directory,
# see the `README.md` for this project.
#
# The two categories of API definitions that impact the manually written segments of the backend:
# - paths:        Defines the URL paths accessible by the API, including parameters and responses.
#                 These are used to to populate the `operations` package (found in
#                 `restapi/operations`), and a handler (to be manually implemented) is generated
#                 for each of these in `configure_variant_service.go`
# - definitions:  Defines the schemas/models in the API, for parameters and for responses, to be
#                 represented by go structs in the code.
#                 These are used to to populate the `models` package and can be referred to
#                 throughout this `swagger.yml` file to describe a `schema` property.

consumes:
- application/json
info:
  description: A model variant service demonstarting CanDIG API best practices
  title: A barebones service for variant calls
  version: 1.0.0
produces:
- application/json
schemes:
- http
swagger: "2.0" # version used by go-swagger tool
paths:
  /variants:
    get:
      operationId: main.get_variants
      summary: Get all variants within genomic range
      parameters:
        - name: chromosome
          in: query
          type: string
          pattern: "^[a-zA-Z0-9]*$"
        - name: start
          in: query
          type: integer
          minimum: 1
        - name: end
          in: query
          type: integer
          minimum: 1
      responses:
        200:
          description: Return variants
          schema:
            type: array
            items:
              $ref: '#/definitions/Variant'
        422:
          description: Query parameters are unprocessable
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"
    post:
      operationId: main.post_variant
      summary: Add a variant to the database
      parameters:
        - name: variant
          in: body
          schema:
            $ref: '#/definitions/Variant'
      responses:
        # TODO Add error code 
        201:
          description: New variant created
          schema:
            $ref: "#/definitions/Variant"
          headers:
            Location:
              type: string
        400:
          description: Variant provided in body does not pass schema validation
          schema:
            $ref: "#/definitions/Error"
        405:
          description: Forbidden to overwrite variant in put
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal error - Variant not created
          schema:
            $ref: "#/definitions/Error"
definitions:
  Error:
    type: object
    required:
      - message
    properties: 
      code:
        type: integer
        format: int32
      message:
        type: string
  Individual:
    type: object
    required:
      - description
    properties:
      id:
        type: string
        format: uuid
        description: Unique internal identifier
        # TODO should we be scarmbling this uuid 
        example: bf3ba75b-8dfe-4619-b832-31c4a087a589
        readOnly: true
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2017-07-21T17:32:28Z"
        readOnly: true
      description:
        type: string
        description: Description of subject (may be external identifier)
        example: "Subject 17"
        minLength: 1
        maxLength: 100
  Call:
    type: object
    required:
      - individual_id
      - variant_id
      - genotype
    properties:
      id:
        type: string
        format: uuid
        description: Unique internal identifier
        example: bf3ba75b-8dfe-4619-b832-31c4a087a589
        readOnly: true
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2017-07-21T17:32:28Z"
        readOnly: true
      individual_id:
        type: integer
        format: int64
        description: Unique internal identifier for the subject
        example: 123
      variant_id:
        type: integer
        format: int64
        description: Unique internal identifier for the variant
        example: 123
      genotype:
        type: string
        description: Called genotype
        example: "0/1"
      format:
        type: string
        description: Additional call information
        example: "GQ:DP:HQ 48:1:51,51"
        minLength: 0
        maxLength: 100
        default: ""
  Variant:
    type: object
    required:
      - chromosome
      - start
      - ref
      - alt
    properties:
      id:
        type: string
        format: uuid
        description: Unique internal identifier
        example: bf3ba75b-8dfe-4619-b832-31c4a087a589
        readOnly: true
      name:
        type: string
        description: Variant name, if any
        example: "rs6054257"
        minLength: 0
        maxLength: 100
        default: ""
      chromosome:
        type: string
        description: Chromosome that the variant occurs on
        example: "chr1"
        minLength: 1
        maxLength: 10
      start:
        type: integer
        description: Beginning location of variant
        example: 14370
        minimum: 1
      ref:
        type: string
        description: Reference bases
        example: "G"
      alt:
        type: string
        description: Alternate (variant) bases
        example: "A"